language: php

php:
  - 5.6
  - 7.0
  - hhvm

services:
  - memcached

before_script:
  - composer install --dev --no-interaction
  - test/travis/apc-setup.sh
  - test/travis/memcache-setup.sh

matrix:
  allow_failures:
    - php: hhvm
